version: 2.1
selenium:
  image: selenium/standalone-firefox
  ports:
  - 4444:4444
jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: circleci/python

    steps:
      - checkout
      - run: python3 main.py


  test:
    working_directory: ~/circleci-python
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run: python3 UnitTest.py

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build