version: 2.1
dependencies:
  pre:
    - sudo pip install -U selenium
jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: sudo pip3 install selenium
      - run: python3 main.py


  test:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: sudo pip3 install selenium
      - run: python3 UnitTest.py

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build