version: 2.1
jobs:
  run_tests:
    docker:
      - image: circleci/python:3.7.4
    steps:
      - checkout
      - run:
          name: Install Python dependencies
          command: |
            echo 'export PATH=~$PATH:~/.local/bin' >> $BASH_ENV && source $BASH_ENV
            pip install --user -r requirements.txt
      - run:
          command: |
            wget  http://selenium-release.storage.googleapis.com/3.141/selenium-server-standalone-3.141.0.jar
            apt-get install -y libglib2.0-0=2.50.3-2 \
                libnss3=2:3.26.2-1.1+deb9u1 \
                libgconf-2-4=3.2.6-4+b1 \
                libfontconfig1=2.11.0-6.7+b1

      - run:
          name: Run unit tests

          command: |
            pytest --junitxml=test-reports/junit.xml --html=test-reports/pytest_report.html --self-contained-html
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports
workflows:
  build_test:
    jobs:
      - run_tests