version: 2.1
dependencies:
  pre:
    - sudo pip install -U selenium
jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: selenium/standalone-chrome

    steps:
      - checkout
      - run: wget https://bootstrap.pypa.io/get-pip.py
      - run: apt-get -y install python3-pip
      - run: python3 -m pip install selenium
      - run: python3 main.py


  test:
    working_directory: ~/circleci-python
    docker:
      - image: cimg/python:3.9.5
    steps:
      - checkout
      - run: wget https://bootstrap.pypa.io/get-pip.py
      - run: apt-get -y install python3-pip
      - run: python3 -m pip install selenium
      - run: python3 UnitTest.py

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build