version: 2.1
jobs:
  run_tests:
    docker:
      - image: circleci/python:3.7.4
    steps:
      - checkout
      - run:
          name: Install Python dependencies
          command: |
            echo 'export PATH=~$PATH:~/.local/bin' >> $BASH_ENV && source $BASH_ENV
            pip install --user -r requirements.txt
      - run:
          command: |
            sudo curl https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -o /chrome.deb
            sudo dpkg -i /chrome.deb || apt-get install -yf
            sudo rm /chrome.deb
            sudo curl https://chromedriver.storage.googleapis.com/2.31/chromedriver_linux64.zip -o /usr/local/bin/chromedriver
            sudo chmod +x /usr/local/bin/chromedriver
            sudo apt-get install -f
      - run:
          name: Run unit tests

          command: |
            pytest --junitxml=test-reports/junit.xml --html=test-reports/pytest_report.html --self-contained-html
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports
workflows:
  build_test:
    jobs:
      - run_tests